# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# Run pre-commit run --all-files to manually run hooks on all files
# You can update your hooks to the latest version automatically by running pre-commit autoupdate. By default, this will bring the hooks to the latest tag on the default branch.
# fail_fast: true
minimum_pre_commit_version: 4.0.1
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: local
    hooks:
      - id: check-hook-updates
        name: Check for pre-commit hook updates
        entry: .pre-commit-hooks/check_hook_updates.py
        language: python
        pass_filenames: false
        always_run: true

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.21
    hooks:
      # Update the uv lockfile
      - id: uv-lock

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: forbid-submodules
      - id: no-commit-to-branch

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.27
    hooks:
      - id: pymarkdown
        args:
          - --disable-rules
          - line-length  # We'll let ruff-format handle line wrapping
          - scan

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pyvista/pre-commit-mypy
    rev: v0.1.0
    hooks:
      - id: mypy
        pass_filenames: false
        args: []  # Using configuration from pyproject.toml
        additional_dependencies:
          - mypy>=1.14.1
          - aiohttp>=3.11.11
          - pydantic>=2.10.5
          - pydantic-settings>=2.7.1
          - python-dotenv>=1.0.1
          - structlog>=25.1.0
          - pytest>=8.3.4
          - pytest-asyncio>=0.25.2
          - pytest-cov>=6.0.0

  # monitor code complexity
  - repo: https://github.com/rubik/xenon
    rev: v0.9.3
    hooks:
    - id: xenon
      args: ['--max-absolute=B', '--max-modules=B', '--max-average=A']

  # .pre-commit-config.yaml
  - repo: https://github.com/christophmeissner/pytest-pre-commit
    rev: 1.0.0
    hooks:
      - id: pytest
        pass_filenames: false
        always_run: true
        additional_dependencies:
          - pytest-asyncio>=0.25.2
          - aiohttp>=3.11.11
          - pydantic>=2.10.5
          - python-dotenv>=1.0.1
          - structlog>=25.1.0
        args:
          - "--durations=0"
          - "--last-failed"
          - "--last-failed-no-failures=all"
          - "--new-first"
          - "-rfEsxXp"
          - "-vvv"
