name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    concurrency: release

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v9.16.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Regular GITHUB_TOKEN is fine since we're not committing
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
          commit: false
          push: false
          tag: true
          vcs_release: true
          root_options: "-vv"
